name: C/C++ CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: search
      run: ls
    - uses: carlosperate/arm-none-eabi-gcc-action@v1
    - name: toolchain
      run: arm-none-eabi-gcc --version
